name: Solve daily puzzles
on:
  schedule:
    - cron: "0 8 * * *"  # At 8am

jobs:
  wordler:
    strategy:
      matrix:
        size: [5, 6, 7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./  # Run against the repo's copy of the action
        with:
          puzzleSize: ${{ matrix.size }}
