name: Test action
on:
  workflow_dispatch:

jobs:
  action-python-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./  # Test against the repo's copy of the action
        with:
          helloName: k2bd
          repeats: 3
