name: Test action
on:
  workflow_dispatch:

jobs:
  wordler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./  # Test against the repo's copy of the action
        with:
          puzzleSize: 6
